# Generated by Django 3.2.4 on 2021-06-30 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('goal', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific', models.CharField(max_length=500)),
                ('measureable', models.CharField(max_length=500)),
                ('attainable', models.CharField(max_length=500)),
                ('relevent', models.CharField(max_length=500)),
                ('timely', models.CharField(max_length=500)),
                ('overall_goal', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='smart_goals.user')),
            ],
        ),
    ]
