# Generated by Django 3.2.4 on 2021-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_goals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='attainable',
            new_name='achievable',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='author',
        ),
        migrations.AddField(
            model_name='goal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
